config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :subscriptions do
      get :cancel, on: :member
    end
  end
end

app/models/spree/subscription.rb
module Spree
  class Subscription < ActiveRecord::Base
    has_many :orders, order: 'completed_at DESC'
    belongs_to :user
    belongs_to :credit_card
    attr_accessible :ship_address_id, :state, :user_id, :interval, :credit_card_id, :resume_on, :bill_address_id

    validates_presence_of :ship_address_id
    validates_presence_of :user_id

    class << self
      def active
        where(state: 'active')
      end

      def ready_for_next_order
        subs = active.select do |sub|
          sub.last_order && sub.interval &&
            sub.last_order.completed_at < sub.interval.weeks.ago
        end

        where(id: subs.collect(&:id))
      end
    end

    def products
      last_order.subscription_products
    end

    def last_shipment_date
      last_order.completed_at if last_order
    end

    def next_shipment_date
      last_order.completed_at.advance(weeks: interval) if last_order
    end

    def cancelled?
      state == 'cancelled'
    end

    def cancel
      update_attribute(:state, 'cancelled')
    end
    alias_method :cancel!, :cancel

    def last_order
      orders.complete.where(payment_state: 'paid').reorder("completed_at DESC").first
    end

    def next_order
      next_order = NullObject.new

      next_order.class_eval do
        def created_at
          '???'
        end
      end

      next_order
    end

    def ship_address
      ::Spree::Address.find(ship_address_id) || last_order.ship_address
    end

    def bill_address
      ::Spree::Address.find(bill_address_id) || last_order.bill_address
    end

  end
end

app/models/subscription_log.rb
class SubscriptionLog < ActiveRecord::Base
  attr_accessible :order_id, :reason
end

app/controllers/spree/admin/subscriptions_controller.rb
module Spree
  module Admin
    class SubscriptionsController < ResourceController
      def index
        params[:q]     ||= {}
        params[:q][:s] ||= 'created_at desc'

        @search = Subscription.ransack(params[:q])
        @subscriptions = @search.result.includes([:user, :orders]).
          page(params.fetch(:page, 1)).
          per(params.fetch(:per_page, Spree::Config[:orders_per_page]))

        respond_with(@subscriptions)
      end

      def cancel
        if @object.cancel
          flash[:success] = flash_message_for(@object, :successfully_cancelled)
          respond_with(@object) do |format|
            format.html { redirect_to collection_url }
          end
        end
      end
    end
  end
end

app/views/spree/admin/subscriptions/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_subscriptions) %>
<% end %>

<% unless @subscriptions.empty? %>
  <table class="index responsive" id="listing_subscriptions" data-hook width="100%">
    <colgroup>
       <col style="width: 5%;">
       <col style="width: 10%;">
       <col style="width: 18%;">
       <col style="width: 18%;">
       <col style="width: 18%;">
       <col style="width: 18%;">
       <col style="width: 5%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_subscriptions_index_headers">
        <th>ID</th>
        <th>State</th>
        <th>Products</th>
        <th>Frequency</th>
        <th>Last Order</th>
        <th>Next Shipment Date</th>
        <th>Resume On</th>
        <th data-hook="admin_subscriptions_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr data-hook="admin_subscriptions_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= subscription.id %></td>
        <td><%= subscription.state %></td>
        <td><%= subscription.products.collect(&:name).to_sentence  %>
        <td>Every <%= subscription.interval %> weeks</td>
        <td>
          <%= link_to subscription.last_order.number, admin_order_path(subscription.last_order) %>
          <br />
          <%= l(subscription.last_order.created_at, format: :long)  %>
        </td>
        <td>
          <%=
            unless subscription.cancelled?
              l(subscription.next_shipment_date, format: :long)
            else
              "N/A"
            end
          -%>
        </td>
        <td><%= l(subscription.resume_on, format: :long) %></td>
        <td class='actions align-center' data-hook="admin_subscriptions_index_row_actions">
          <%=
            unless subscription.cancelled?
              link_to_with_icon 'icon-cancel', 'Cancel', cancel_admin_subscription_path(subscription),
                no_text: true, data: { confirm: t(:are_you_sure), action: 'remove' }
            end
          -%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= t(:no_subscriptions_found)%>
  </div>
<% end %>

<%= paginate @subscriptions %>

app/views/spree/users/_subscriptions.html.erb
<div data-hook="account_my_subscriptions">

  <h3><%= t(:my_subscriptions) %></h3>
  <% if @user.subscriptions.present? %>
    <table class="subscription-summary">
      <thead>
        <tr>
          <th><%= t(:products) %></th>
          <th><%= t(:last_shipped_on) %></th>
          <th><%= t(:next_shipment) %> </th>
          <th><%= t(:status) %></th>
        </tr>
      </thead>
      <tbody>
        <% @user.subscriptions.each do |subscription| %>
          <tr>
            <td><%= subscription.products.collect(&:name).to_sentence %></td>
            <td><%= subscription.last_shipment_date %></td>
            <td><%= subscription.next_shipment_date %></td>
            <td><%= t(subscription.state, :scope => 'subscription_state', default: t('subscription_state.active')).titleize %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p><%= t(:you_have_no_subscriptions_yet) %></p>
  <% end %>
  <br />

</div>